### ISSUE TITLE
Do you have a unity deepmimic humanoid model?

### ISSUE THREAD

**Issue by hellozjj** [sloganking/FbxToMimic#10]
I want to retarget the animtion in unity to deepmimic humanoid, but I don't know how to create a humanoid like deepmimic in unity. So if you have one, could you share it with me? Or could you give me some advice how I can get this or create this? Thanks a lot.

**Comment by sloganking** [comment]
While porting DeepMimic to a game engine such as Unity is interesting, I am not experienced with Unity and I do not have a DeepMimic Humanoid model for it. I will close this issue for now since it is not specifically related to this repository.

You may however be interested in ``DReCon`` which is Ubisoft's attempt to port DeepMimic to a game engine.

https://youtu.be/o_DhNqHazKY

https://static-wordpress.akamaized.net/montreal.ubisoft.com/wp-content/uploads/2019/11/13214229/DReCon.pdf
